@startuml

note as N1
This diagram is meant to give a conceptual overview of the most important
classes and relations. It does not resemble every detail nor do all types
and names have to be the exact same ones as in the implementation.
For example I am using a generic "List" whereas the implementation is done 
via a QVector.

end note

package control {
	abstract class AbstractScannerStrategy {
		{abstract} + scanIcons()
		{abstract} + scanClassifications()
	}
	package strategies {
		class FreedesktopScannerStrategy --|> AbstractScannerStrategy
		class GenericXmlScannerStrategy --|> AbstractScannerStrategy
	}
}

package view {
	class ClassificationFilterView
	
	class IconSetBrowser {
		List<ClassificationFilterView> classificationFilters
		+ IconSetBrowser (AbstractScannerStrategy iconScannerStrategy)
		+ setIconSet (IconSet iconSet)
		+ updateIconSet()
	}
}

package model {
	class IconClassification {
		String name
		IconClassification parent
		List<IconClassification> children
		+ boolean hasParent()
		+ boolean hasChildren()
		+ IconClassification getParent()
		+ List<IconClassification> getChildren()
		+ addChild()
		+ setParent()
	}
	
	class IconSet {
		List<Icon> icons
		List<IconClassification> classifications
		AbconScannerStrategy scannerStrategy 
	}
	
	class Icon {
		String file
		List<IconClassification> classifications
	}
}

IconSetBrowser o-- AbstractScannerStrategy
IconSetBrowser o-- ClassificationFilterView

Icon o-- IconClassification
IconSet o-- Icon
IconSet o-- IconClassification
IconSet o- AbstractScannerStrategy

IconSetBrowser -- IconSet

note bottom of IconClassification: Ways of classifying and grouping icons within a set.\nFor example resolution, category or target device.\nNested classifications are possible (e.g. "high-resolution/256").

note top of FreedesktopScannerStrategy: An exemplary implementation that parses theme files\nas often seen with Linux icon sets.

note top of GenericXmlScannerStrategy: A generic way of defining icon set structures via XML.\nIn case no specific file format is existant.\nFollowing this apporach Icon Set Forge is hopefully useful\nfor many "non-programmers".

@enduml