@startuml
package control {
	abstract class IconScannerStrategy {
		{abstract} + scanIconDirectoryForCategories
		{abstract} + scanIconDirectoryForResolutions
	}
	class FreedesktopIconScannerStrategy --|> IconScannerStrategy
}

note top of FreedesktopIconScannerStrategy: First: An exemplary implementation that expects icon folders\narraged as often seen with Linux icon sets (category/resolution).\n\nNext step would be automatic parsing of theme.index files! 

package view {
	class CategoryView
	class ResolutionView
	class IconSetBrowser {
		+ IconSetBrowser (iconScannerStrategy : IconScannerStrategy)
	}
}

IconSetBrowser o-- IconScannerStrategy
IconSetBrowser o-- ResolutionView
IconSetBrowser o-- CategoryView

@enduml