@startuml
package control {
	abstract class AbstractIconScannerStrategy {
		{abstract} + scanIconDirectoryForCategories
		{abstract} + scanIconDirectoryForResolutions
	}
	package strategies {
		class FreedesktopIconScannerStrategy --|> AbstractIconScannerStrategy
	}
}

note top of FreedesktopIconScannerStrategy: First: An exemplary implementation that parses theme-files\n as often seen with Linux icon sets.

package view {
	class CategoryView
	class ResolutionView
	class IconSetBrowser {
		+ IconSetBrowser (iconScannerStrategy : AbstractAbstractIconScannerStrategy)
	}
}


IconSetBrowser o-- AbstractIconScannerStrategy
IconSetBrowser o-- ResolutionView
IconSetBrowser o-- CategoryView

@enduml