@startuml 

package model {
	class IconClassification {
		String name
		IconClassification* parent
		QVector<shared_ptr<IconClassification>> children
		QVector<shared_ptr<IconClassification::InsertCommand>> insertCommandChain
		bool immutable
		bool groupBy
		bool selected
		- setParent()
		+ addChild()
	}
	
	class IconSet {
		unique_ptr<QVector<Icon>> icons
		unique_ptr<IconClassification> classifications
		unique_ptr<QVector<IconGroup>> groups
	}
	
	class IconComponent {
		{abstract} const &QImage getRepresentativeImage()
	}
	
	class IconGroup {
		QVector<IconComponent *> children
	}
	
	class Icon {
		QString name
		QImage image
		Icon* link
		QVector<shared_ptr<IconClassification>> classifications
		+setImage(QImage image)
		+setLink(QLink link)
		+isLinkType()
		+addClassification(shared_ptr<IconClassification classification)
		+insertIntoClassification(shared_ptr<IconClassification classification)
	}
	
	package access {
		class ClassificationTreeModel {
				IconSet* iconSet
			}
			
		class IconListModel {
			IconSet* iconSet
		}
	}
	
	Icon -- IconClassification
	IconSet *-- Icon
	IconSet *-- IconClassification
	IconClassification *-- IconClassification : organized as a tree
	IconComponent <|- Icon
	IconComponent <|-- IconGroup
	ClassificationTreeModel --> IconSet
	IconListModel --> IconSet
}


package view {
	class MainWindow {
	}
	
	class IconSetBrowser {
		QListView iconSetView
		QTreeView	classificationTreeView
	}
}


package control {
	class Coordinator {
		int activeIconSetIndex;
		QVector<IconSetOperator> openIconSets
		+openIconSet(AbstractScannerStrategy scannerStrategy)
		..slots..
		+setActiveIconSet(int index);
		+applyOperation(some action)
	}
	class IconSetOperator {
		unique_ptr<IconSet> iconSet
		unique_ptr<AbstractScannerStrategy> scannerStrategy
		QUndoStack undoStack
		+ IconSetOperator(AbstractScannerStrategy scannerStrategy)
		+ void applyOperation(some action)
	}
	
	Coordinator *-IconSetOperator
}


package scannerstrategies {
		abstract class AbstractScannerStrategy {
			+ {abstract} unique_ptr<IconSet> loadIconSet()
			+ {abstract} boolean saveIconSet(const IconSet &iconSet)
		}
		class FreedesktopScannerStrategy --|> AbstractScannerStrategy
		class GenericXmlScannerStrategy --|> AbstractScannerStrategy
	}


MainWindow .. Coordinator : sends action signals >
MainWindow *-- IconSetBrowser
IconSetBrowser .. IconListModel : < provides data
IconSetBrowser .. ClassificationTreeModel : < provides data
IconSetOperator *-- IconSet : owns >
AbstractScannerStrategy --> IconSet : instantiates >
IconSetOperator *-- AbstractScannerStrategy


note top of GenericXmlScannerStrategy
A generic way of defining simple icon set structures 
via XML (or JSON?). Following this apporach <i>Icon Set Forge</i>
is hopefully useful for many "non-programmers".
endnote

@enduml